from typing import override, TYPE_CHECKING

from pydantic import BaseModel

from ._base import ActionResult, IAction
from ._buy_to_charge import BuyToChargeAction
from ._energy_deficiency import EnergyDeficiencyAction, EnergySource
from ._energy_excess import EnergyExcessAction, EnergyFeed
from ._price import PriceAction, PriceLevel

if TYPE_CHECKING:
    from .. import IMicrogrid


class CompositeResult(BaseModel):
    generated_energy: float
    price_level: PriceLevel
    total_load: float
    energy_sold: float
    energy_bought: float
    price: float


class CompositeBasicAction(IAction):
    """Defines one Action to execute multiple Actions in sequence.

    Attributes:
        price_action (PriceAction): The price action for calculating the total load in response to the price.
        energy_excess_action (EnergyExcessAction): The energy excess action for selling energy or store it to a battery.
        energy_deficiency_action (EnergyDeficiencyAction): The energy deficiency action for buying energy or using it from a battery.
    """

    possible_energy_feeds = [EnergyFeed.EXTERNAL_GRID, EnergyFeed.BATTERY]
    possible_energy_sources = [EnergySource.EXTERNAL_GRID, EnergySource.BATTERY]
    ACTIONS = [
        [price, excess, deficiency]
        for price in range(PriceAction.calc_action_space())
        for excess in range(
            EnergyExcessAction.calc_action_space(possible_feeds=[EnergyFeed.EXTERNAL_GRID, EnergyFeed.BATTERY])
        )
        for deficiency in range(
            EnergyDeficiencyAction.calc_action_space(
                possible_sources=[EnergySource.EXTERNAL_GRID, EnergySource.BATTERY]
            )
        )
    ]

    def __init__(
        self,
        price_action: PriceAction,
        energy_excess_action: EnergyExcessAction,
        energy_deficiency_action: EnergyDeficiencyAction,
    ):
        super().__init__()
        self.price_action: PriceAction = price_action
        self.energy_excess_action: EnergyExcessAction = energy_excess_action
        self.energy_deficiency_action: EnergyDeficiencyAction = energy_deficiency_action

    @override
    def execute(self, microgrid: "IMicrogrid", time_step: int) -> CompositeResult:
        """Executes all actions in the logical order.

        Args:
            microgrid: environment to manipulate
            time_step: current time step in hours

        Returns:
              List of ActionResult objects, each containing the result of the executed action.
        """
        # Get the energy generated by DER
        generated_energy = microgrid.distributed_energy_resources.current_generation(
            microgrid.external_grid.current_time
        )

        # Execute the PriceAction: Get the total load consumption in response to the price
        total_load = self.price_action.execute(microgrid, time_step)
        # Try to fulfill the required energy with the available energy from DER
        available_energy = generated_energy - total_load

        # Initialize with zero values in case of perfect balance
        energy_result = ActionResult(energy_sold=0, energy_bought=0, price=0)

        if available_energy > 0:
            # Energy Excess (Store or sell)
            self.energy_excess_action.set_available_energy(available_energy)
            energy_result = self.energy_excess_action.execute(microgrid, time_step)
        elif available_energy < 0:
            # Energy Deficiency (Use Battery or buy)
            self.energy_deficiency_action.set_missing_energy(-available_energy)
            energy_result = self.energy_deficiency_action.execute(microgrid, time_step)
        # If available_energy is exactly 0, there's a perfect balance - no action needed

        return CompositeResult(
            generated_energy=generated_energy,
            price_level=self.price_action.price_level,
            total_load=total_load,
            energy_sold=energy_result.energy_sold,
            energy_bought=energy_result.energy_bought,
            price=energy_result.price,
        )

    @classmethod
    @override
    def calc_action_space(cls) -> int:
        """Calculates the size for the composite action space, by multiplying the action_space for all actions.

        Example:
            Given a composite action of 3 different actions with sizes of [3, 2, 4] as action_space,
            this method will calculate 3 * 2 * 4 = 24.

        Returns:
            size of the composite action space
        """
        return len(cls.ACTIONS)

    @classmethod
    @override
    def from_action_space(cls, action: int, **kwargs) -> "CompositeBasicAction":
        actions = cls.ACTIONS[action]
        return cls(
            price_action=PriceAction.from_action_space(actions[0]),
            energy_excess_action=EnergyExcessAction.from_action_space(
                actions[1], possible_feeds=cls.possible_energy_feeds
            ),
            energy_deficiency_action=EnergyDeficiencyAction.from_action_space(
                actions[2], possible_sources=cls.possible_energy_sources
            ),
        )

    @override
    def to_action_space(self) -> int:
        price_act = self.price_action.to_action_space()
        energy_excess_act = self.energy_excess_action.to_action_space()
        energy_deficiency_act = self.energy_deficiency_action.to_action_space()

        act = [price_act, energy_excess_act, energy_deficiency_act]
        return self.ACTIONS.index(act)

    def __repr__(self):
        return f"""CompositeAction(
    {repr(self.price_action)},
    {repr(self.energy_excess_action)},
    {repr(self.energy_deficiency_action)}
)"""


class CompositeCarAction(IAction):
    """Defines one Action to execute multiple Actions in sequence.

    Attributes:
        price_action (PriceAction): The price action for calculating the total load in response to the price.
        energy_excess_action (EnergyExcessAction): The energy excess action for selling energy or store it to a battery.
        energy_deficiency_action (EnergyDeficiencyAction): The energy deficiency action for buying energy or using it from a battery.
    """

    possible_energy_feeds = [EnergyFeed.EXTERNAL_GRID, EnergyFeed.BATTERY, EnergyFeed.CAR_BATTERY]
    possible_energy_sources = [EnergySource.EXTERNAL_GRID, EnergySource.BATTERY, EnergySource.CAR_BATTERY]
    ACTIONS = [
        [price, excess, deficiency, buy]
        for price in range(PriceAction.calc_action_space())
        for excess in range(
            EnergyExcessAction.calc_action_space(
                possible_feeds=[EnergyFeed.EXTERNAL_GRID, EnergyFeed.BATTERY, EnergyFeed.CAR_BATTERY]
            )
        )
        for deficiency in range(
            EnergyDeficiencyAction.calc_action_space(
                possible_sources=[EnergySource.EXTERNAL_GRID, EnergySource.BATTERY, EnergySource.CAR_BATTERY]
            )
        )
        for buy in range(BuyToChargeAction.calc_action_space())
    ]

    def __init__(
        self,
        price_action: PriceAction,
        energy_excess_action: EnergyExcessAction,
        energy_deficiency_action: EnergyDeficiencyAction,
        buy_to_charge_action: BuyToChargeAction,
    ):
        super().__init__()
        self.price_action: PriceAction = price_action
        self.energy_excess_action: EnergyExcessAction = energy_excess_action
        self.energy_deficiency_action: EnergyDeficiencyAction = energy_deficiency_action
        self.buy_to_charge_action: BuyToChargeAction = buy_to_charge_action

    @override
    def execute(self, microgrid: "IMicrogrid", time_step: int) -> CompositeResult:
        """Executes all actions in the logical order.

        Args:
            microgrid: environment to manipulate
            time_step: current time step in hours

        Returns:
              List of ActionResult objects, each containing the result of the executed action.
        """
        # Get the energy generated by DER
        generated_energy = microgrid.distributed_energy_resources.current_generation(
            microgrid.external_grid.current_time
        )

        # Execute the PriceAction: Get the total load consumption in response to the price
        total_load = self.price_action.execute(microgrid, time_step)
        # Try to fulfill the required energy with the available energy from DER
        if (
            time_step == microgrid.car_battery.target_time
            and microgrid.car_battery.SoC >= microgrid.car_battery.desired_soc
        ):
            microgrid.car_battery.discharge(microgrid.car_battery.desired_soc)
            microgrid.car_battery.setCanBeCharged(False)
            if microgrid.car_battery.target_time + microgrid.car_battery.time_away >= 24:
                print("Wrong config car_target_time + car_time_away must be less than 24")
                print(f"target_time: {microgrid.car_battery.target_time}")
                print(f"time_away:{microgrid.car_battery.time_away}")
        if time_step == (microgrid.car_battery.target_time + microgrid.car_battery.time_away):
            microgrid.car_battery.setCanBeCharged(True)
        available_energy = generated_energy - total_load

        # Initialize with zero values in case of perfect balance
        energy_result = ActionResult(energy_sold=0, energy_bought=0, price=0)

        if available_energy > 0:
            # Energy Excess (Store or sell)
            self.energy_excess_action.set_available_energy(available_energy)
            energy_result = self.energy_excess_action.execute(microgrid, time_step)
        elif available_energy < 0:
            # Energy Deficiency (Use Battery or buy)
            self.energy_deficiency_action.set_missing_energy(-available_energy)
            energy_result = self.energy_deficiency_action.execute(microgrid, time_step)
        # If available_energy is exactly 0, there's a perfect balance - no action needed
        bat_charge = self.buy_to_charge_action.execute(microgrid, time_step)

        return CompositeResult(
            generated_energy=generated_energy,
            price_level=self.price_action.price_level,
            total_load=total_load,
            energy_sold=energy_result.energy_sold + bat_charge.energy_sold,
            energy_bought=energy_result.energy_bought + bat_charge.energy_bought,
            price=energy_result.price + bat_charge.energy_bought,
        )

    @classmethod
    @override
    def calc_action_space(cls) -> int:
        """Calculates the size for the composite action space, by multiplying the action_space for all actions.

        Example:
            Given a composite action of 3 different actions with sizes of [3, 2, 4] as action_space,
            this method will calculate 3 * 2 * 4 = 24.

        Returns:
            size of the composite action space
        """
        return len(cls.ACTIONS)

    @classmethod
    @override
    def from_action_space(cls, action: int, **kwargs) -> "CompositeBasicAction":
        """Factory method for creating a composite action from an action space index.

        Example:
            >>> import numpy as np
            >>> output = np.random.sample(20)
            >>> action = np.argmax(output)
            >>> composite_action = CompositeBasicAction.from_action_space(action)

        Args:
            action: index of the action to create

        Returns:
            A CompositeAction instance with initialized actions
        """
        actions = cls.ACTIONS[action]
        return cls(
            price_action=PriceAction.from_action_space(actions[0]),
            energy_excess_action=EnergyExcessAction.from_action_space(
                actions[1], possible_feeds=cls.possible_energy_feeds
            ),
            energy_deficiency_action=EnergyDeficiencyAction.from_action_space(
                actions[2], possible_sources=cls.possible_energy_sources
            ),
            buy_to_charge_action=BuyToChargeAction.from_action_space(actions[3]),
        )

    @override
    def to_action_space(self) -> int:
        price_act = self.price_action.to_action_space()
        energy_excess_act = self.energy_excess_action.to_action_space()
        energy_deficiency_act = self.energy_deficiency_action.to_action_space()
        buy_to_charge_act = self.buy_to_charge_action.to_action_space()

        act = [price_act, energy_excess_act, energy_deficiency_act, buy_to_charge_act]
        return self.ACTIONS.index(act)

    def __repr__(self):
        return f"""CompositeAction(
    {repr(self.price_action)},
    {repr(self.energy_excess_action)},
    {repr(self.energy_deficiency_action)}
)"""
